# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://idemo.bspb.ru/auth?response_type=code&client_id=1&redirect_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fsuccess&prefetch_uri=https%3A%2F%2Fidemo.bspb.ru%2Flogin%2Fprefetch&force_new_session=true")
    self.driver.set_window_size(1468, 886)
    self.driver.find_element(By.ID, "login-button").click()
    self.driver.find_element(By.ID, "login-otp-button").click()
    self.driver.find_element(By.ID, "cards-overview-index").click()
    self.driver.find_element(By.CSS_SELECTOR, "#card-details-ownbank-10068 .card-set-pin > .link-title").click()
    self.driver.find_element(By.ID, "calculator-button-1").click()
    self.driver.find_element(By.ID, "calculator-button-2").click()
    self.driver.find_element(By.ID, "calculator-button-3").click()
    self.driver.find_element(By.ID, "calculator-button-5").click()
    self.driver.find_element(By.ID, "set-pin").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.ID, "confirm").click()
  
